### ISSUE TITLE
Migration and other plataforms projects

### ISSUE THREAD

**Issue by napcat** [tylerbuchea/cordova-android-crosswalk#18]
Hello,

I'm about to try your migration tool.
The current application that I'm building will run on android, ios and windows phone.

If I install the migration tool and run it on my project will it break the ios and windows phone plataform projects? Or it will only effect the android build?

Can I still run the "cordova run android" after I install the crosswalk?

Can I revert the migration?

Sorry if it looks like dumb questions, but I dont want to break my project.

Thank you

**Comment by tylerbuchea** [comment]
Hey napcat,

* The tool only effects the Android build.
* You can still and should use all the Cordova commands as usual. Including "cordova run android".
* The tool does not support reversion and probably never will. Mostly because all the stuff it changes is in "myProject/platforms/android". So all you have to do is run "cordova platform remove android" and then add it back "cordova platform add android" then the Crosswalk stuff will be gone and you'll have a regular version of android ready to rock.

There really isn't much I can think of that this tool could break that isn't easily fixable. So I hope you enjoy it and if you have any more questions feel free to email me tyler@buchea.com
