### ISSUE TITLE
 I can’t use Chrome Developer Tools to debug

### ISSUE THREAD

**Issue by carlosvillu** [tylerbuchea/cordova-android-crosswalk#20]
Hi,

I´m trying to migrate a Cordova project with your project, but, after executing this series of commands I can’t use Chrome Developer Tools to debug:

$ cordova -v
3.5.0-0.2.7

$ android list
Available Android targets:
----------
id: 1 or "android-19"
     Name: Android 4.4.2
     Type: Platform
     API level: 19
     Revision: 4
     Skins: HVGA, QVGA, WQVGA400, WQVGA432, WSVGA, WVGA800 (default), WVGA854, WXGA720, WXGA800, WXGA800-7in
 Tag/ABIs : default/armeabi-v7a, default/x86

$ cordova create /tmp/cordova-test es.test Test
$ cd /tmp/cordova-test
$ cordova platform add android
$ cordova build android
$ cordova-android-crosswalk -x 7.36.154.14 -a arm -f
$ cordova run android

The app is working great in the device with CrossWalk. But in chrome://inspect and click in inspect I get this:

![captura de pantalla 2015-03-12 a las 11 40 37](https://cloud.githubusercontent.com/assets/179462/6616273/a60b9c06-c8ac-11e4-9143-c833b2d4f35d.png)

But Chrome DevTool works properly if I don't migrate my project to CrossWalk.

Thx!

**Comment by tylerbuchea** [comment]
It's probably because you're using an older version of Crosswalk and Cordova or are you getting the same bug on the current Crosswalk and accompanying Cordova dependency?

I probably won't spend any time on this because bugs are expected when using the force flag. I'm not saying it's not an issue just that it's outside of the scope of the tool to flawlessly support sub-current versions.

That being said clean PRs are always welcome if you find a nice fix. I'll keep this open until you reply. Thanks for the input and for reading my long winded response :p
